- manual/source/classes/contributed_definitions/mpes-structure.rst
Remove unnecessary references on NXmpes NeXus page.
- Remove information about developers ('we', 'FAIRmat', ...)
- Remove reference to already standardised definitions
- Improve wording
> Initial fix to MPES structure on html page

- dev_tools/nyaml2nxdl/nyaml2nxdl.py
- dev_tools/nyaml2nxdl/nyaml2nxdl_helper.py
- To extend the nyaml2nxdl converter by adding the `--store-nxdl` flag allowing users to choose whether the input file `nxdl` should be stored at the end of output `yaml` file by comment.
> Adding flag for store_nxdl option in nyaml2nxdl converter.

- base_classes/NXroot.nxdl.xml
There was a difference for the NXroot generated by the `nyaml2nxdl` in the fairmat branch and the one from #101. This commit fixes NXroot to work with `nyaml2nxdl@fairmat`
> Fix NXroot nxdl

- dev_tools/nyaml2nxdl/nyaml2nxdl_backward_tools.py
- dev_tools/nyaml2nxdl/nyaml2nxdl_forward_tools.py
- dev_tools/tests/data/doc_yaml2nxdl.yaml
- dev_tools/tests/data/ref_doc_yaml2nxdl.nxdl.xml
Allows for writing multiple list items in root-level docstring of a nyaml file.
- nyaml2nxdl_forward_tool:
- Check if root-level doc is a string and non-empty (this was implemented before).
- Check if root-level doc is instead a list and _one_ of the list elements is not empty.
- If true, the doc is handled as any other multi-component doc (this includes any xref docs).
- The test data for the forward tool has also been extended to cover this use case.
- Typo fix in backwards tool.
Fixes #119.
> Allow xref in root-level docstring

- Makefile
- README.md
- nyaml.mk
This adds several things:
- Proper build of `nxdl.xml` files even if they are not present. This is now completely based on the available yaml files
- Removal of `nyaml` for loop
- Add a new Makefile `nyaml.mk` for building nyaml targets to be invoked like this `make -f nyaml.mk`
> Refine makefiles

- base_classes/NXtransformations.nxdl.xml
- base_classes/nyaml/NXtransformations.yaml
Based on this PR: https://github.com/nexusformat/definitions/pull/1278 and this issue https://github.com/nexusformat/definitions/issues/1269.
Fixes #88
> Updates NXtransformations docs

- contributed_definitions/NXsensor_scan.nxdl.xml
- contributed_definitions/nyaml/NXsensor_scan.yaml
`NXsensor_scan` was accidentally converted to a base class in https://github.com/FAIRmat-NFDI/nexus_definitions/commit/db6632204654dcc1f7052a130a85b1fd18b6f137.
This breaks `NXiv_temp` and `NXsts`.
This PR reverts the change.
> Makes sensor scan an appdef again

- base_classes/NXsource.nxdl.xml
- base_classes/nyaml/NXsource.yaml
- contributed_definitions/NXdeflector.nxdl.xml
- contributed_definitions/nyaml/NXdeflector.yaml
Adds some groups/fields to NXsource and NXdeflector. For NXsource specifically, generic `(NXaperture)`, `(NXdeflector)`, and `(NXlens_em)` are added which allow for a more detailed description of the individual components of the source.
These concepts inside NXsource were shown to be useful for the PHI XPS data reader (see [here](https://github.com/FAIRmat-NFDI/pynxtools-xps/blob/00bdee3cd15451e86a34597c9120ebf1c65f47c2/pynxtools_xps/config/config_phi.json#L50) for the config file making use of them), but should be generally enough also for other sources.
> Additions to NXsource and NXdeflector

- contributed_definitions/NXmpes.nxdl.xml
- contributed_definitions/nyaml/NXmpes.yaml
This changes `associated_source` and `associated_beam` to NX_CHARs to just link them to the other concept.
I think it's the better approach than actually hard-linking the groups, because
1. We get recursion when viewing the file when both groups are present
2. The referred base classes `NXsource` and `NXbeam` are not the correct ones. It should be `NXmpes/ENTRY/INSTRUMENT/NXsource`/`NXbeam` but we cannot actually refer to this in the nxdl (at least that's what I think). This is also problematic when this gets parsed because NOMAD expects a class `NXsource`, which for example does not contain `HHG laser` as we define this in the appdef.
There might be solutions to support the current way but I think making this text links is much simpler and I don't really have an argument for actually …
> Change associated_beam and _source to NX_CHAR

- contributed_definitions/NXfabrication.nxdl.xml
- contributed_definitions/NXlockin.nxdl.xml
- contributed_definitions/NXsts.nxdl.xml
- contributed_definitions/nyaml/NXfabrication.yaml
- contributed_definitions/nyaml/NXlockin.yaml
- contributed_definitions/nyaml/NXsts.yaml
Bringing all the plots like `single_points` and `line_scan` on the same level and out of the NXdata group.
> Update appdef for nxsts

- base_classes/NXenvironment.nxdl.xml
- base_classes/nyaml/NXenvironment.yaml
- contributed_definitions/NXactuator.nxdl.xml
- contributed_definitions/NXcalibration.nxdl.xml
- contributed_definitions/NXcollectioncolumn.nxdl.xml
- contributed_definitions/NXelectronanalyser.nxdl.xml
- contributed_definitions/NXenergydispersion.nxdl.xml
- contributed_definitions/NXmanipulator.nxdl.xml
- contributed_definitions/NXpid.nxdl.xml
- contributed_definitions/NXresolution.nxdl.xml
- contributed_definitions/nyaml/NXactuator.yaml
- contributed_definitions/nyaml/NXcalibration.yaml
- contributed_definitions/nyaml/NXcollectioncolumn.yaml
- contributed_definitions/nyaml/NXelectronanalyser.yaml
- contributed_definitions/nyaml/NXenergydispersion.yaml
- contributed_definitions/nyaml/NXmanipulator.yaml
- contributed_definitions/nyaml/NXpid.yaml
- contributed_definitions/nyaml/NXresolution.yaml
This allows for more flexibility when defining the default chain within NXmpes NeXus files.
> Add default attribute to MPES-related base classes

- contributed_definitions/NXellipsometry.nxdl.xml
- contributed_definitions/NXfabrication.nxdl.xml
- contributed_definitions/NXhistory.nxdl.xml
- contributed_definitions/NXopt.nxdl.xml
- contributed_definitions/NXopt_window.nxdl.xml
- contributed_definitions/NXraman.nxdl.xml
- contributed_definitions/nyaml/NXellipsometry.yaml
- contributed_definitions/nyaml/NXfabrication.yaml
- contributed_definitions/nyaml/NXhistory.yaml
- contributed_definitions/nyaml/NXopt.yaml
- contributed_definitions/nyaml/NXopt_window.yaml
- contributed_definitions/nyaml/NXraman.yaml
- dev_tools/utils/nxdl_utils.py
This PR is a full rework of the NXopt definition. The for this was used from NXmpes and NXem.
NXopt was first defined from NXellipsometry. Therefore, some concepts are present in the current NXopt form, which makes sense to define NXellipsometry(NXopt), but not for e.g. NXraman(NXopt) or NXpl(NXopt). This rework should generalize NXopt in a first step, before in an upcoming workshop final refinements are done.
Added/Modified Parts:
- General entry information
- Various NXuser fields
- Various instrument Devices
- Reference frames with description (needs to be worked out later in detail)
- Added two additional fundamental angles required for scattering/emission experiments and sample rotation
- moved/added calibration and exp. resolution
- NXbeams with polarization description
- Specified …
> Overhaul of NXopt

- contributed_definitions/NXmpes_arpes.nxdl.xml
- contributed_definitions/nyaml/NXmpes_arpes.yaml
The nyaml file was changed a bit because I also ran the backwards conversion. Note that inline comments in the nyaml are not being picked up during the nyaml2nxdl conversion. I either removed unneeded comments or put them into the official docs.
Eventually, we need to discuss how we want to handle the issue that NXdata derived base classes are not recognized as NXdata. This is probably also a problem for other tools that don't have base class extensions yet.
Fixes #233
> Temporarily use NXdata in NXmpes_arpes

- base_classes/NXtransformations.nxdl.xml
- base_classes/nyaml/NXtransformations.yaml
- contributed_definitions/NXcoordinate_system.nxdl.xml
- contributed_definitions/NXcoordinate_system_set.nxdl.xml
- contributed_definitions/NXem_conventions.nxdl.xml
- contributed_definitions/nyaml/NXcoordinate_system.yaml
- contributed_definitions/nyaml/NXcoordinate_system_set.yaml
- contributed_definitions/nyaml/NXem_conventions.yaml
Fixes #143.
EDIT: an example for converting from one CS to another by using `NXcoordinate_system/(NXtransformations)` can be found [here](https://github.com/FAIRmat-NFDI/pynxtools-xps/blob/4e4107b7505ca0513d99d99b4159e36cd64b947c/examples/coordinate_system/vms-cs-fixed.nxs).
> Define usage of NXtransformations and NXcoordinate_system(_set)

- applications/NXarpes.nxdl.xml
- applications/nyaml/NXarpes.yaml
This is a proposal to refer NXmpes from NXarpes to avoid confusion for users of the definition.
This relates to #74 (i.e., whether it should refer to NXphotoemission _or_ NXmpes).
It might also be a point for discussion whether NXarpes is a legacy version and newer experiments should be collected in NXmpes. Do we also support converting NXarpes to NXmpes/NXmpes_arpes?
> Add a reference to NXmpes from NXarpes

- .github/workflows/fairmat-build-pages.yaml
This changes the deploy action in the `.fairmat-build-pages.yaml` workflow to https://github.com/peaceiris/actions-gh-pages, which has a `force-orphan` option, so that the history of the `fairmat-docs` branch always only contains the docs for the active branches.
> Fix docs CI to only keep orphan branch

- base_classes/NXbeam.nxdl.xml
- base_classes/NXenvironment.nxdl.xml
- base_classes/nyaml/NXbeam.yaml
- base_classes/nyaml/NXenvironment.yaml
- contributed_definitions/NXmpes.nxdl.xml
- contributed_definitions/nyaml/NXmpes.yaml
@rettigl @domna this bundles all of the changes we were discussing in the last few days, also with respect to the requests from Stefan and Uwe. My plan is to first merge this and then rebase the `mpes-liquid` branch and finally make the necessary changes on `NXmpes_liquid` there.
> Small modifications to clarify NXmpes

- base_classes/NXdata.nxdl.xml
- base_classes/nyaml/NXdata.yaml
- contributed_definitions/NXdata_mpes.nxdl.xml
- contributed_definitions/NXmpes.nxdl.xml
- contributed_definitions/NXmpes_arpes.nxdl.xml
- contributed_definitions/nyaml/NXdata_mpes.yaml
- contributed_definitions/nyaml/NXmpes.yaml
- contributed_definitions/nyaml/NXmpes_arpes.yaml
This enables the option to describe where the signal data of an NXdata comes from. It's a similar concept as the `AXISNAME_depends`. It's just a proposal open for discussion and I'm not entirely sure if this is the right path to do it. So I welcome your feedback @lukaspie and @rettigl. Also general feedback from @FAIRmat-NFDI/areab is welcome.
Different options could be:
- Additionally or instead provide a `depends` field for the NXdata group to denote that it was linked to somewhere else. This is essentially a shortcut for writing out `AXISNAME_depends` + `DATA_depends` if they belong to the same target group.
- Allowing an array or different mechanism here to also describe composite data, e.g., if we combine two detectors together and need to denote which axis comes from where. There …
> NXdata linking of signal

- contributed_definitions/NXxrd_pan.nxdl.xml
- contributed_definitions/nyaml/NXxrd_pan.yaml
1. A quick fix for NeXus incompatible concept name `2theta` for XRD use case.
2. Replace NXcollection for NXobject.
> fix 2theta and use NXobject instead of collection.

- dev_tools/docs/nxdl_index.py
- manual/source/classes/contributed_definitions/optical-spectroscopy-structure.rst
- manual/source/ellipsometry-structure.rst
- manual/source/index.rst
- manual/source/optical-spectroscopy-structure.rst
This shall update the webpage, which is accessible for users via the TOC on the left of on the page: https://fairmat-nfdi.github.io/nexus_definitions/index.html# under optical spectroscopy.
any notes regarding general optical spectroscopy or Raman were not present.
Have to test if the links are messed up, as i renamed a .rst file from ellipsometry-structure to optical-spectroscopy-structure.
> Update optical spec website to include optical spectroscopy and raman

- dev_tools/tests/test_nxdl_utils.py
- dev_tools/utils/nxdl_utils.py
This adds some edge cases to the documentation of the `get_nx_namefit` function for better understanding
> Add edge cases to namefit documentation

- contributed_definitions/NXellipsometry.nxdl.xml
- contributed_definitions/NXoptical_spectroscopy.nxdl.xml
- contributed_definitions/NXraman.nxdl.xml
- contributed_definitions/nyaml/NXellipsometry.yaml
- contributed_definitions/nyaml/NXoptical_spectroscopy.yaml
- contributed_definitions/nyaml/NXraman.yaml
These adds mostly some notes from the Ellipsometry and Raman workshop to the .yaml files: Wishes and ideas, what to add in the future. As nothing is mandatory, before the final submission to the NIAC, mostly nothing was changed.
Only a few lamp types were added. Some easy changes might break parser from pynxtools-raman and pynxtools-ellips - hence only notes were added.
> Add workshop notes from ellip and raman

- contributed_definitions/NXmanipulator.nxdl.xml
- contributed_definitions/NXmpes.nxdl.xml
- contributed_definitions/NXxps.nxdl.xml
- contributed_definitions/nyaml/NXmanipulator.yaml
- contributed_definitions/nyaml/NXmpes.yaml
- contributed_definitions/nyaml/NXxps.yaml
These changes are necessary because during standardization, NIAC sugggested changes to the base classes that we were bringing in, but this was not yet reflected in the application definitions.
I also added an optional monochromator to `NXxps`, following suggestions in https://github.com/FAIRmat-NFDI/nexus_definitions/pull/147.
For checking that everything is correct now, these are the base classes that were changed so far:
- NXaperture
- NXbeam
- NXdetector
- NXenvironment
- NXinstrument
- NXmonochromator
- NXnote
- NXprocess
- NXsample
- NXsample_component
- NXsensor
- NXsource
And these are the ones that we added and are now standardized:
- NXactuator
- NXactivity
- NXcalibration
- NXcomponent
- NXdistortion
- NXelectron_detector
- NXfabrication
- NXhistory
- NXregistration
- …
> MPES: further changes from NIAC

- base_classes/NXparameters.nxdl.xml
- base_classes/nyaml/NXparameters.yaml
- contributed_definitions/NXmpes.nxdl.xml
- contributed_definitions/nyaml/NXmpes.yaml
@rettigl I am not sure how one would write this now, both on the appdef level and in the file. Do you have a good suggestion? Even with this approach here, it is failing when I write `['kinetic_energy']` into the file
> Fixes in NXmpes

- applications/NXmpes_arpes.nxdl.xml
- applications/NXxps.nxdl.xml
In https://github.com/nexusformat/definitions/pull/1424, following discussion in https://github.com/nexusformat/definitions/pull/1410, it was suggested that we remove the initially proposed `@reference` attribute in `NXdata`. Additionally, the reviewers suggested to not use a named `data(NXdata)` group, but rather go with an unnamed `NXdata` to enable multiple views on the data.
These two suggestions were implemented in https://github.com/nexusformat/definitions/pull/1424 for the application definition `NXmpes`, but not for the extending application definitions `NXxps` and `NXmpes_arpes`. This PR points to that branch and fixes these issues also in the extending application definitions.
cc @phyy-nx
> remove remaining reference attribute from `NXxps` and `NXmpes`
